//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace PhoneLogic.Core.AppServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobSummary", Namespace="http://schemas.datacontract.org/2004/07/PhoneLogic.DataContracts")]
    public partial class JobSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AbandonedField;
        
        private int CallbackField;
        
        private int InQueueField;
        
        private int InboundCallsField;
        
        private string JobNumberField;
        
        private int LeftMessageField;
        
        private int NoAgentsField;
        
        private int OutboundCallField;
        
        private int PlacedCallField;
        
        private string TollFreeNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Abandoned {
            get {
                return this.AbandonedField;
            }
            set {
                if ((this.AbandonedField.Equals(value) != true)) {
                    this.AbandonedField = value;
                    this.RaisePropertyChanged("Abandoned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Callback {
            get {
                return this.CallbackField;
            }
            set {
                if ((this.CallbackField.Equals(value) != true)) {
                    this.CallbackField = value;
                    this.RaisePropertyChanged("Callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InQueue {
            get {
                return this.InQueueField;
            }
            set {
                if ((this.InQueueField.Equals(value) != true)) {
                    this.InQueueField = value;
                    this.RaisePropertyChanged("InQueue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InboundCalls {
            get {
                return this.InboundCallsField;
            }
            set {
                if ((this.InboundCallsField.Equals(value) != true)) {
                    this.InboundCallsField = value;
                    this.RaisePropertyChanged("InboundCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeftMessage {
            get {
                return this.LeftMessageField;
            }
            set {
                if ((this.LeftMessageField.Equals(value) != true)) {
                    this.LeftMessageField = value;
                    this.RaisePropertyChanged("LeftMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoAgents {
            get {
                return this.NoAgentsField;
            }
            set {
                if ((this.NoAgentsField.Equals(value) != true)) {
                    this.NoAgentsField = value;
                    this.RaisePropertyChanged("NoAgents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OutboundCall {
            get {
                return this.OutboundCallField;
            }
            set {
                if ((this.OutboundCallField.Equals(value) != true)) {
                    this.OutboundCallField = value;
                    this.RaisePropertyChanged("OutboundCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlacedCall {
            get {
                return this.PlacedCallField;
            }
            set {
                if ((this.PlacedCallField.Equals(value) != true)) {
                    this.PlacedCallField = value;
                    this.RaisePropertyChanged("PlacedCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TollFreeNumber {
            get {
                return this.TollFreeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TollFreeNumberField, value) != true)) {
                    this.TollFreeNumberField = value;
                    this.RaisePropertyChanged("TollFreeNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueDetail", Namespace="http://schemas.datacontract.org/2004/07/PhoneLogic.DataContracts")]
    public partial class QueueDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CallerIdField;
        
        private string IdField;
        
        private string JobNumberField;
        
        private string TimeInField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerId {
            get {
                return this.CallerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerIdField, value) != true)) {
                    this.CallerIdField = value;
                    this.RaisePropertyChanged("CallerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeIn {
            get {
                return this.TimeInField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeInField, value) != true)) {
                    this.TimeInField = value;
                    this.RaisePropertyChanged("TimeIn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueSummary", Namespace="http://schemas.datacontract.org/2004/07/PhoneLogic.DataContracts")]
    public partial class QueueSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int InQueueField;
        
        private string JobNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InQueue {
            get {
                return this.InQueueField;
            }
            set {
                if ((this.InQueueField.Equals(value) != true)) {
                    this.InQueueField = value;
                    this.RaisePropertyChanged("InQueue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveCall", Namespace="http://schemas.datacontract.org/2004/07/PhoneLogic.DataContracts")]
    public partial class ActiveCall : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CallerIdField;
        
        private string ConferenceUriField;
        
        private string IdField;
        
        private string JobNumberField;
        
        private string RecruiterUriField;
        
        private string TimeInField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerId {
            get {
                return this.CallerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerIdField, value) != true)) {
                    this.CallerIdField = value;
                    this.RaisePropertyChanged("CallerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConferenceUri {
            get {
                return this.ConferenceUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ConferenceUriField, value) != true)) {
                    this.ConferenceUriField = value;
                    this.RaisePropertyChanged("ConferenceUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecruiterUri {
            get {
                return this.RecruiterUriField;
            }
            set {
                if ((object.ReferenceEquals(this.RecruiterUriField, value) != true)) {
                    this.RecruiterUriField = value;
                    this.RaisePropertyChanged("RecruiterUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeIn {
            get {
                return this.TimeInField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeInField, value) != true)) {
                    this.TimeInField = value;
                    this.RaisePropertyChanged("TimeIn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppServiceReference.IPhoneLogicService")]
    public interface IPhoneLogicService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetJobSummary", ReplyAction="http://tempuri.org/IPhoneLogicService/GetJobSummaryResponse")]
        System.IAsyncResult BeginGetJobSummary(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary> EndGetJobSummary(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetQueueDetail", ReplyAction="http://tempuri.org/IPhoneLogicService/GetQueueDetailResponse")]
        System.IAsyncResult BeginGetQueueDetail(string jobNumber, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> EndGetQueueDetail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetAllCallsInQueue", ReplyAction="http://tempuri.org/IPhoneLogicService/GetAllCallsInQueueResponse")]
        System.IAsyncResult BeginGetAllCallsInQueue(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> EndGetAllCallsInQueue(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetMyQueuedCalls", ReplyAction="http://tempuri.org/IPhoneLogicService/GetMyQueuedCallsResponse")]
        System.IAsyncResult BeginGetMyQueuedCalls(string sipAddress, System.AsyncCallback callback, object asyncState);
        
        int EndGetMyQueuedCalls(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetMyQueueSummary", ReplyAction="http://tempuri.org/IPhoneLogicService/GetMyQueueSummaryResponse")]
        System.IAsyncResult BeginGetMyQueueSummary(string sipAddress, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary> EndGetMyQueueSummary(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetRecruitersOnline", ReplyAction="http://tempuri.org/IPhoneLogicService/GetRecruitersOnlineResponse")]
        System.IAsyncResult BeginGetRecruitersOnline(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetRecruitersOnline(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetRecruitersAvailable", ReplyAction="http://tempuri.org/IPhoneLogicService/GetRecruitersAvailableResponse")]
        System.IAsyncResult BeginGetRecruitersAvailable(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetRecruitersAvailable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/GetActiveCalls", ReplyAction="http://tempuri.org/IPhoneLogicService/GetActiveCallsResponse")]
        System.IAsyncResult BeginGetActiveCalls(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall> EndGetActiveCalls(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/RecruiterDialOut", ReplyAction="http://tempuri.org/IPhoneLogicService/RecruiterDialOutResponse")]
        System.IAsyncResult BeginRecruiterDialOut(string recruiterUri, string jobNumber, string numberToDial, int callbackId, System.AsyncCallback callback, object asyncState);
        
        void EndRecruiterDialOut(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/TransferCall", ReplyAction="http://tempuri.org/IPhoneLogicService/TransferCallResponse")]
        System.IAsyncResult BeginTransferCall(string id, string recruiterUri, System.AsyncCallback callback, object asyncState);
        
        void EndTransferCall(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/SilentMonitorCall", ReplyAction="http://tempuri.org/IPhoneLogicService/SilentMonitorCallResponse")]
        System.IAsyncResult BeginSilentMonitorCall(string id, string sipAddress, System.AsyncCallback callback, object asyncState);
        
        void EndSilentMonitorCall(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/BargeIntoCall", ReplyAction="http://tempuri.org/IPhoneLogicService/BargeIntoCallResponse")]
        System.IAsyncResult BeginBargeIntoCall(string id, string sipAddress, System.AsyncCallback callback, object asyncState);
        
        void EndBargeIntoCall(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneLogicService/DispatchCallInQueue", ReplyAction="http://tempuri.org/IPhoneLogicService/DispatchCallInQueueResponse")]
        System.IAsyncResult BeginDispatchCallInQueue(string id, string sipAddress, System.AsyncCallback callback, object asyncState);
        
        void EndDispatchCallInQueue(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneLogicServiceChannel : PhoneLogic.Core.AppServiceReference.IPhoneLogicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetJobSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetJobSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetQueueDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetQueueDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCallsInQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCallsInQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMyQueuedCallsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMyQueuedCallsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMyQueueSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMyQueueSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRecruitersOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRecruitersOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRecruitersAvailableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRecruitersAvailableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetActiveCallsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetActiveCallsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneLogicServiceClient : System.ServiceModel.ClientBase<PhoneLogic.Core.AppServiceReference.IPhoneLogicService>, PhoneLogic.Core.AppServiceReference.IPhoneLogicService {
        
        private BeginOperationDelegate onBeginGetJobSummaryDelegate;
        
        private EndOperationDelegate onEndGetJobSummaryDelegate;
        
        private System.Threading.SendOrPostCallback onGetJobSummaryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetQueueDetailDelegate;
        
        private EndOperationDelegate onEndGetQueueDetailDelegate;
        
        private System.Threading.SendOrPostCallback onGetQueueDetailCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllCallsInQueueDelegate;
        
        private EndOperationDelegate onEndGetAllCallsInQueueDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCallsInQueueCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMyQueuedCallsDelegate;
        
        private EndOperationDelegate onEndGetMyQueuedCallsDelegate;
        
        private System.Threading.SendOrPostCallback onGetMyQueuedCallsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMyQueueSummaryDelegate;
        
        private EndOperationDelegate onEndGetMyQueueSummaryDelegate;
        
        private System.Threading.SendOrPostCallback onGetMyQueueSummaryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRecruitersOnlineDelegate;
        
        private EndOperationDelegate onEndGetRecruitersOnlineDelegate;
        
        private System.Threading.SendOrPostCallback onGetRecruitersOnlineCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRecruitersAvailableDelegate;
        
        private EndOperationDelegate onEndGetRecruitersAvailableDelegate;
        
        private System.Threading.SendOrPostCallback onGetRecruitersAvailableCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetActiveCallsDelegate;
        
        private EndOperationDelegate onEndGetActiveCallsDelegate;
        
        private System.Threading.SendOrPostCallback onGetActiveCallsCompletedDelegate;
        
        private BeginOperationDelegate onBeginRecruiterDialOutDelegate;
        
        private EndOperationDelegate onEndRecruiterDialOutDelegate;
        
        private System.Threading.SendOrPostCallback onRecruiterDialOutCompletedDelegate;
        
        private BeginOperationDelegate onBeginTransferCallDelegate;
        
        private EndOperationDelegate onEndTransferCallDelegate;
        
        private System.Threading.SendOrPostCallback onTransferCallCompletedDelegate;
        
        private BeginOperationDelegate onBeginSilentMonitorCallDelegate;
        
        private EndOperationDelegate onEndSilentMonitorCallDelegate;
        
        private System.Threading.SendOrPostCallback onSilentMonitorCallCompletedDelegate;
        
        private BeginOperationDelegate onBeginBargeIntoCallDelegate;
        
        private EndOperationDelegate onEndBargeIntoCallDelegate;
        
        private System.Threading.SendOrPostCallback onBargeIntoCallCompletedDelegate;
        
        private BeginOperationDelegate onBeginDispatchCallInQueueDelegate;
        
        private EndOperationDelegate onEndDispatchCallInQueueDelegate;
        
        private System.Threading.SendOrPostCallback onDispatchCallInQueueCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PhoneLogicServiceClient() {
        }
        
        public PhoneLogicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneLogicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneLogicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneLogicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetJobSummaryCompletedEventArgs> GetJobSummaryCompleted;
        
        public event System.EventHandler<GetQueueDetailCompletedEventArgs> GetQueueDetailCompleted;
        
        public event System.EventHandler<GetAllCallsInQueueCompletedEventArgs> GetAllCallsInQueueCompleted;
        
        public event System.EventHandler<GetMyQueuedCallsCompletedEventArgs> GetMyQueuedCallsCompleted;
        
        public event System.EventHandler<GetMyQueueSummaryCompletedEventArgs> GetMyQueueSummaryCompleted;
        
        public event System.EventHandler<GetRecruitersOnlineCompletedEventArgs> GetRecruitersOnlineCompleted;
        
        public event System.EventHandler<GetRecruitersAvailableCompletedEventArgs> GetRecruitersAvailableCompleted;
        
        public event System.EventHandler<GetActiveCallsCompletedEventArgs> GetActiveCallsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RecruiterDialOutCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> TransferCallCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SilentMonitorCallCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> BargeIntoCallCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DispatchCallInQueueCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetJobSummary(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetJobSummary(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary> PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetJobSummary(System.IAsyncResult result) {
            return base.Channel.EndGetJobSummary(result);
        }
        
        private System.IAsyncResult OnBeginGetJobSummary(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetJobSummary(callback, asyncState);
        }
        
        private object[] OnEndGetJobSummary(System.IAsyncResult result) {
            System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary> retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetJobSummary(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetJobSummaryCompleted(object state) {
            if ((this.GetJobSummaryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetJobSummaryCompleted(this, new GetJobSummaryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetJobSummaryAsync() {
            this.GetJobSummaryAsync(null);
        }
        
        public void GetJobSummaryAsync(object userState) {
            if ((this.onBeginGetJobSummaryDelegate == null)) {
                this.onBeginGetJobSummaryDelegate = new BeginOperationDelegate(this.OnBeginGetJobSummary);
            }
            if ((this.onEndGetJobSummaryDelegate == null)) {
                this.onEndGetJobSummaryDelegate = new EndOperationDelegate(this.OnEndGetJobSummary);
            }
            if ((this.onGetJobSummaryCompletedDelegate == null)) {
                this.onGetJobSummaryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetJobSummaryCompleted);
            }
            base.InvokeAsync(this.onBeginGetJobSummaryDelegate, null, this.onEndGetJobSummaryDelegate, this.onGetJobSummaryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetQueueDetail(string jobNumber, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetQueueDetail(jobNumber, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetQueueDetail(System.IAsyncResult result) {
            return base.Channel.EndGetQueueDetail(result);
        }
        
        private System.IAsyncResult OnBeginGetQueueDetail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobNumber = ((string)(inValues[0]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetQueueDetail(jobNumber, callback, asyncState);
        }
        
        private object[] OnEndGetQueueDetail(System.IAsyncResult result) {
            System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetQueueDetail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetQueueDetailCompleted(object state) {
            if ((this.GetQueueDetailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetQueueDetailCompleted(this, new GetQueueDetailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetQueueDetailAsync(string jobNumber) {
            this.GetQueueDetailAsync(jobNumber, null);
        }
        
        public void GetQueueDetailAsync(string jobNumber, object userState) {
            if ((this.onBeginGetQueueDetailDelegate == null)) {
                this.onBeginGetQueueDetailDelegate = new BeginOperationDelegate(this.OnBeginGetQueueDetail);
            }
            if ((this.onEndGetQueueDetailDelegate == null)) {
                this.onEndGetQueueDetailDelegate = new EndOperationDelegate(this.OnEndGetQueueDetail);
            }
            if ((this.onGetQueueDetailCompletedDelegate == null)) {
                this.onGetQueueDetailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetQueueDetailCompleted);
            }
            base.InvokeAsync(this.onBeginGetQueueDetailDelegate, new object[] {
                        jobNumber}, this.onEndGetQueueDetailDelegate, this.onGetQueueDetailCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetAllCallsInQueue(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllCallsInQueue(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetAllCallsInQueue(System.IAsyncResult result) {
            return base.Channel.EndGetAllCallsInQueue(result);
        }
        
        private System.IAsyncResult OnBeginGetAllCallsInQueue(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetAllCallsInQueue(callback, asyncState);
        }
        
        private object[] OnEndGetAllCallsInQueue(System.IAsyncResult result) {
            System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetAllCallsInQueue(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCallsInQueueCompleted(object state) {
            if ((this.GetAllCallsInQueueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCallsInQueueCompleted(this, new GetAllCallsInQueueCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllCallsInQueueAsync() {
            this.GetAllCallsInQueueAsync(null);
        }
        
        public void GetAllCallsInQueueAsync(object userState) {
            if ((this.onBeginGetAllCallsInQueueDelegate == null)) {
                this.onBeginGetAllCallsInQueueDelegate = new BeginOperationDelegate(this.OnBeginGetAllCallsInQueue);
            }
            if ((this.onEndGetAllCallsInQueueDelegate == null)) {
                this.onEndGetAllCallsInQueueDelegate = new EndOperationDelegate(this.OnEndGetAllCallsInQueue);
            }
            if ((this.onGetAllCallsInQueueCompletedDelegate == null)) {
                this.onGetAllCallsInQueueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCallsInQueueCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllCallsInQueueDelegate, null, this.onEndGetAllCallsInQueueDelegate, this.onGetAllCallsInQueueCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetMyQueuedCalls(string sipAddress, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMyQueuedCalls(sipAddress, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetMyQueuedCalls(System.IAsyncResult result) {
            return base.Channel.EndGetMyQueuedCalls(result);
        }
        
        private System.IAsyncResult OnBeginGetMyQueuedCalls(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sipAddress = ((string)(inValues[0]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetMyQueuedCalls(sipAddress, callback, asyncState);
        }
        
        private object[] OnEndGetMyQueuedCalls(System.IAsyncResult result) {
            int retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetMyQueuedCalls(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMyQueuedCallsCompleted(object state) {
            if ((this.GetMyQueuedCallsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMyQueuedCallsCompleted(this, new GetMyQueuedCallsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMyQueuedCallsAsync(string sipAddress) {
            this.GetMyQueuedCallsAsync(sipAddress, null);
        }
        
        public void GetMyQueuedCallsAsync(string sipAddress, object userState) {
            if ((this.onBeginGetMyQueuedCallsDelegate == null)) {
                this.onBeginGetMyQueuedCallsDelegate = new BeginOperationDelegate(this.OnBeginGetMyQueuedCalls);
            }
            if ((this.onEndGetMyQueuedCallsDelegate == null)) {
                this.onEndGetMyQueuedCallsDelegate = new EndOperationDelegate(this.OnEndGetMyQueuedCalls);
            }
            if ((this.onGetMyQueuedCallsCompletedDelegate == null)) {
                this.onGetMyQueuedCallsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMyQueuedCallsCompleted);
            }
            base.InvokeAsync(this.onBeginGetMyQueuedCallsDelegate, new object[] {
                        sipAddress}, this.onEndGetMyQueuedCallsDelegate, this.onGetMyQueuedCallsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetMyQueueSummary(string sipAddress, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMyQueueSummary(sipAddress, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary> PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetMyQueueSummary(System.IAsyncResult result) {
            return base.Channel.EndGetMyQueueSummary(result);
        }
        
        private System.IAsyncResult OnBeginGetMyQueueSummary(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sipAddress = ((string)(inValues[0]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetMyQueueSummary(sipAddress, callback, asyncState);
        }
        
        private object[] OnEndGetMyQueueSummary(System.IAsyncResult result) {
            System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary> retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetMyQueueSummary(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMyQueueSummaryCompleted(object state) {
            if ((this.GetMyQueueSummaryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMyQueueSummaryCompleted(this, new GetMyQueueSummaryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMyQueueSummaryAsync(string sipAddress) {
            this.GetMyQueueSummaryAsync(sipAddress, null);
        }
        
        public void GetMyQueueSummaryAsync(string sipAddress, object userState) {
            if ((this.onBeginGetMyQueueSummaryDelegate == null)) {
                this.onBeginGetMyQueueSummaryDelegate = new BeginOperationDelegate(this.OnBeginGetMyQueueSummary);
            }
            if ((this.onEndGetMyQueueSummaryDelegate == null)) {
                this.onEndGetMyQueueSummaryDelegate = new EndOperationDelegate(this.OnEndGetMyQueueSummary);
            }
            if ((this.onGetMyQueueSummaryCompletedDelegate == null)) {
                this.onGetMyQueueSummaryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMyQueueSummaryCompleted);
            }
            base.InvokeAsync(this.onBeginGetMyQueueSummaryDelegate, new object[] {
                        sipAddress}, this.onEndGetMyQueueSummaryDelegate, this.onGetMyQueueSummaryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetRecruitersOnline(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRecruitersOnline(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetRecruitersOnline(System.IAsyncResult result) {
            return base.Channel.EndGetRecruitersOnline(result);
        }
        
        private System.IAsyncResult OnBeginGetRecruitersOnline(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetRecruitersOnline(callback, asyncState);
        }
        
        private object[] OnEndGetRecruitersOnline(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetRecruitersOnline(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRecruitersOnlineCompleted(object state) {
            if ((this.GetRecruitersOnlineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRecruitersOnlineCompleted(this, new GetRecruitersOnlineCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRecruitersOnlineAsync() {
            this.GetRecruitersOnlineAsync(null);
        }
        
        public void GetRecruitersOnlineAsync(object userState) {
            if ((this.onBeginGetRecruitersOnlineDelegate == null)) {
                this.onBeginGetRecruitersOnlineDelegate = new BeginOperationDelegate(this.OnBeginGetRecruitersOnline);
            }
            if ((this.onEndGetRecruitersOnlineDelegate == null)) {
                this.onEndGetRecruitersOnlineDelegate = new EndOperationDelegate(this.OnEndGetRecruitersOnline);
            }
            if ((this.onGetRecruitersOnlineCompletedDelegate == null)) {
                this.onGetRecruitersOnlineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRecruitersOnlineCompleted);
            }
            base.InvokeAsync(this.onBeginGetRecruitersOnlineDelegate, null, this.onEndGetRecruitersOnlineDelegate, this.onGetRecruitersOnlineCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetRecruitersAvailable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRecruitersAvailable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetRecruitersAvailable(System.IAsyncResult result) {
            return base.Channel.EndGetRecruitersAvailable(result);
        }
        
        private System.IAsyncResult OnBeginGetRecruitersAvailable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetRecruitersAvailable(callback, asyncState);
        }
        
        private object[] OnEndGetRecruitersAvailable(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetRecruitersAvailable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRecruitersAvailableCompleted(object state) {
            if ((this.GetRecruitersAvailableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRecruitersAvailableCompleted(this, new GetRecruitersAvailableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRecruitersAvailableAsync() {
            this.GetRecruitersAvailableAsync(null);
        }
        
        public void GetRecruitersAvailableAsync(object userState) {
            if ((this.onBeginGetRecruitersAvailableDelegate == null)) {
                this.onBeginGetRecruitersAvailableDelegate = new BeginOperationDelegate(this.OnBeginGetRecruitersAvailable);
            }
            if ((this.onEndGetRecruitersAvailableDelegate == null)) {
                this.onEndGetRecruitersAvailableDelegate = new EndOperationDelegate(this.OnEndGetRecruitersAvailable);
            }
            if ((this.onGetRecruitersAvailableCompletedDelegate == null)) {
                this.onGetRecruitersAvailableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRecruitersAvailableCompleted);
            }
            base.InvokeAsync(this.onBeginGetRecruitersAvailableDelegate, null, this.onEndGetRecruitersAvailableDelegate, this.onGetRecruitersAvailableCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginGetActiveCalls(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetActiveCalls(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall> PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndGetActiveCalls(System.IAsyncResult result) {
            return base.Channel.EndGetActiveCalls(result);
        }
        
        private System.IAsyncResult OnBeginGetActiveCalls(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginGetActiveCalls(callback, asyncState);
        }
        
        private object[] OnEndGetActiveCalls(System.IAsyncResult result) {
            System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall> retVal = ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndGetActiveCalls(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetActiveCallsCompleted(object state) {
            if ((this.GetActiveCallsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetActiveCallsCompleted(this, new GetActiveCallsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetActiveCallsAsync() {
            this.GetActiveCallsAsync(null);
        }
        
        public void GetActiveCallsAsync(object userState) {
            if ((this.onBeginGetActiveCallsDelegate == null)) {
                this.onBeginGetActiveCallsDelegate = new BeginOperationDelegate(this.OnBeginGetActiveCalls);
            }
            if ((this.onEndGetActiveCallsDelegate == null)) {
                this.onEndGetActiveCallsDelegate = new EndOperationDelegate(this.OnEndGetActiveCalls);
            }
            if ((this.onGetActiveCallsCompletedDelegate == null)) {
                this.onGetActiveCallsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetActiveCallsCompleted);
            }
            base.InvokeAsync(this.onBeginGetActiveCallsDelegate, null, this.onEndGetActiveCallsDelegate, this.onGetActiveCallsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginRecruiterDialOut(string recruiterUri, string jobNumber, string numberToDial, int callbackId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRecruiterDialOut(recruiterUri, jobNumber, numberToDial, callbackId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndRecruiterDialOut(System.IAsyncResult result) {
            base.Channel.EndRecruiterDialOut(result);
        }
        
        private System.IAsyncResult OnBeginRecruiterDialOut(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string recruiterUri = ((string)(inValues[0]));
            string jobNumber = ((string)(inValues[1]));
            string numberToDial = ((string)(inValues[2]));
            int callbackId = ((int)(inValues[3]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginRecruiterDialOut(recruiterUri, jobNumber, numberToDial, callbackId, callback, asyncState);
        }
        
        private object[] OnEndRecruiterDialOut(System.IAsyncResult result) {
            ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndRecruiterDialOut(result);
            return null;
        }
        
        private void OnRecruiterDialOutCompleted(object state) {
            if ((this.RecruiterDialOutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RecruiterDialOutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RecruiterDialOutAsync(string recruiterUri, string jobNumber, string numberToDial, int callbackId) {
            this.RecruiterDialOutAsync(recruiterUri, jobNumber, numberToDial, callbackId, null);
        }
        
        public void RecruiterDialOutAsync(string recruiterUri, string jobNumber, string numberToDial, int callbackId, object userState) {
            if ((this.onBeginRecruiterDialOutDelegate == null)) {
                this.onBeginRecruiterDialOutDelegate = new BeginOperationDelegate(this.OnBeginRecruiterDialOut);
            }
            if ((this.onEndRecruiterDialOutDelegate == null)) {
                this.onEndRecruiterDialOutDelegate = new EndOperationDelegate(this.OnEndRecruiterDialOut);
            }
            if ((this.onRecruiterDialOutCompletedDelegate == null)) {
                this.onRecruiterDialOutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecruiterDialOutCompleted);
            }
            base.InvokeAsync(this.onBeginRecruiterDialOutDelegate, new object[] {
                        recruiterUri,
                        jobNumber,
                        numberToDial,
                        callbackId}, this.onEndRecruiterDialOutDelegate, this.onRecruiterDialOutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginTransferCall(string id, string recruiterUri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTransferCall(id, recruiterUri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndTransferCall(System.IAsyncResult result) {
            base.Channel.EndTransferCall(result);
        }
        
        private System.IAsyncResult OnBeginTransferCall(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            string recruiterUri = ((string)(inValues[1]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginTransferCall(id, recruiterUri, callback, asyncState);
        }
        
        private object[] OnEndTransferCall(System.IAsyncResult result) {
            ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndTransferCall(result);
            return null;
        }
        
        private void OnTransferCallCompleted(object state) {
            if ((this.TransferCallCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TransferCallCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TransferCallAsync(string id, string recruiterUri) {
            this.TransferCallAsync(id, recruiterUri, null);
        }
        
        public void TransferCallAsync(string id, string recruiterUri, object userState) {
            if ((this.onBeginTransferCallDelegate == null)) {
                this.onBeginTransferCallDelegate = new BeginOperationDelegate(this.OnBeginTransferCall);
            }
            if ((this.onEndTransferCallDelegate == null)) {
                this.onEndTransferCallDelegate = new EndOperationDelegate(this.OnEndTransferCall);
            }
            if ((this.onTransferCallCompletedDelegate == null)) {
                this.onTransferCallCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTransferCallCompleted);
            }
            base.InvokeAsync(this.onBeginTransferCallDelegate, new object[] {
                        id,
                        recruiterUri}, this.onEndTransferCallDelegate, this.onTransferCallCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginSilentMonitorCall(string id, string sipAddress, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSilentMonitorCall(id, sipAddress, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndSilentMonitorCall(System.IAsyncResult result) {
            base.Channel.EndSilentMonitorCall(result);
        }
        
        private System.IAsyncResult OnBeginSilentMonitorCall(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            string sipAddress = ((string)(inValues[1]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginSilentMonitorCall(id, sipAddress, callback, asyncState);
        }
        
        private object[] OnEndSilentMonitorCall(System.IAsyncResult result) {
            ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndSilentMonitorCall(result);
            return null;
        }
        
        private void OnSilentMonitorCallCompleted(object state) {
            if ((this.SilentMonitorCallCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SilentMonitorCallCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SilentMonitorCallAsync(string id, string sipAddress) {
            this.SilentMonitorCallAsync(id, sipAddress, null);
        }
        
        public void SilentMonitorCallAsync(string id, string sipAddress, object userState) {
            if ((this.onBeginSilentMonitorCallDelegate == null)) {
                this.onBeginSilentMonitorCallDelegate = new BeginOperationDelegate(this.OnBeginSilentMonitorCall);
            }
            if ((this.onEndSilentMonitorCallDelegate == null)) {
                this.onEndSilentMonitorCallDelegate = new EndOperationDelegate(this.OnEndSilentMonitorCall);
            }
            if ((this.onSilentMonitorCallCompletedDelegate == null)) {
                this.onSilentMonitorCallCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSilentMonitorCallCompleted);
            }
            base.InvokeAsync(this.onBeginSilentMonitorCallDelegate, new object[] {
                        id,
                        sipAddress}, this.onEndSilentMonitorCallDelegate, this.onSilentMonitorCallCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginBargeIntoCall(string id, string sipAddress, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBargeIntoCall(id, sipAddress, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndBargeIntoCall(System.IAsyncResult result) {
            base.Channel.EndBargeIntoCall(result);
        }
        
        private System.IAsyncResult OnBeginBargeIntoCall(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            string sipAddress = ((string)(inValues[1]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginBargeIntoCall(id, sipAddress, callback, asyncState);
        }
        
        private object[] OnEndBargeIntoCall(System.IAsyncResult result) {
            ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndBargeIntoCall(result);
            return null;
        }
        
        private void OnBargeIntoCallCompleted(object state) {
            if ((this.BargeIntoCallCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BargeIntoCallCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BargeIntoCallAsync(string id, string sipAddress) {
            this.BargeIntoCallAsync(id, sipAddress, null);
        }
        
        public void BargeIntoCallAsync(string id, string sipAddress, object userState) {
            if ((this.onBeginBargeIntoCallDelegate == null)) {
                this.onBeginBargeIntoCallDelegate = new BeginOperationDelegate(this.OnBeginBargeIntoCall);
            }
            if ((this.onEndBargeIntoCallDelegate == null)) {
                this.onEndBargeIntoCallDelegate = new EndOperationDelegate(this.OnEndBargeIntoCall);
            }
            if ((this.onBargeIntoCallCompletedDelegate == null)) {
                this.onBargeIntoCallCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBargeIntoCallCompleted);
            }
            base.InvokeAsync(this.onBeginBargeIntoCallDelegate, new object[] {
                        id,
                        sipAddress}, this.onEndBargeIntoCallDelegate, this.onBargeIntoCallCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPhoneLogicService.BeginDispatchCallInQueue(string id, string sipAddress, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDispatchCallInQueue(id, sipAddress, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneLogic.Core.AppServiceReference.IPhoneLogicService.EndDispatchCallInQueue(System.IAsyncResult result) {
            base.Channel.EndDispatchCallInQueue(result);
        }
        
        private System.IAsyncResult OnBeginDispatchCallInQueue(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            string sipAddress = ((string)(inValues[1]));
            return ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).BeginDispatchCallInQueue(id, sipAddress, callback, asyncState);
        }
        
        private object[] OnEndDispatchCallInQueue(System.IAsyncResult result) {
            ((PhoneLogic.Core.AppServiceReference.IPhoneLogicService)(this)).EndDispatchCallInQueue(result);
            return null;
        }
        
        private void OnDispatchCallInQueueCompleted(object state) {
            if ((this.DispatchCallInQueueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DispatchCallInQueueCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DispatchCallInQueueAsync(string id, string sipAddress) {
            this.DispatchCallInQueueAsync(id, sipAddress, null);
        }
        
        public void DispatchCallInQueueAsync(string id, string sipAddress, object userState) {
            if ((this.onBeginDispatchCallInQueueDelegate == null)) {
                this.onBeginDispatchCallInQueueDelegate = new BeginOperationDelegate(this.OnBeginDispatchCallInQueue);
            }
            if ((this.onEndDispatchCallInQueueDelegate == null)) {
                this.onEndDispatchCallInQueueDelegate = new EndOperationDelegate(this.OnEndDispatchCallInQueue);
            }
            if ((this.onDispatchCallInQueueCompletedDelegate == null)) {
                this.onDispatchCallInQueueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDispatchCallInQueueCompleted);
            }
            base.InvokeAsync(this.onBeginDispatchCallInQueueDelegate, new object[] {
                        id,
                        sipAddress}, this.onEndDispatchCallInQueueDelegate, this.onDispatchCallInQueueCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneLogic.Core.AppServiceReference.IPhoneLogicService CreateChannel() {
            return new PhoneLogicServiceClientChannel(this);
        }
        
        private class PhoneLogicServiceClientChannel : ChannelBase<PhoneLogic.Core.AppServiceReference.IPhoneLogicService>, PhoneLogic.Core.AppServiceReference.IPhoneLogicService {
            
            public PhoneLogicServiceClientChannel(System.ServiceModel.ClientBase<PhoneLogic.Core.AppServiceReference.IPhoneLogicService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetJobSummary(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetJobSummary", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary> EndGetJobSummary(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary> _result = ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.JobSummary>)(base.EndInvoke("GetJobSummary", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetQueueDetail(string jobNumber, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = jobNumber;
                System.IAsyncResult _result = base.BeginInvoke("GetQueueDetail", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> EndGetQueueDetail(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> _result = ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail>)(base.EndInvoke("GetQueueDetail", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllCallsInQueue(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllCallsInQueue", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> EndGetAllCallsInQueue(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail> _result = ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueDetail>)(base.EndInvoke("GetAllCallsInQueue", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMyQueuedCalls(string sipAddress, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = sipAddress;
                System.IAsyncResult _result = base.BeginInvoke("GetMyQueuedCalls", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetMyQueuedCalls(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetMyQueuedCalls", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMyQueueSummary(string sipAddress, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = sipAddress;
                System.IAsyncResult _result = base.BeginInvoke("GetMyQueueSummary", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary> EndGetMyQueueSummary(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary> _result = ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.QueueSummary>)(base.EndInvoke("GetMyQueueSummary", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRecruitersOnline(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRecruitersOnline", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetRecruitersOnline(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetRecruitersOnline", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRecruitersAvailable(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRecruitersAvailable", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetRecruitersAvailable(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetRecruitersAvailable", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetActiveCalls(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetActiveCalls", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall> EndGetActiveCalls(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall> _result = ((System.Collections.Generic.List<PhoneLogic.Core.AppServiceReference.ActiveCall>)(base.EndInvoke("GetActiveCalls", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRecruiterDialOut(string recruiterUri, string jobNumber, string numberToDial, int callbackId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = recruiterUri;
                _args[1] = jobNumber;
                _args[2] = numberToDial;
                _args[3] = callbackId;
                System.IAsyncResult _result = base.BeginInvoke("RecruiterDialOut", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRecruiterDialOut(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RecruiterDialOut", _args, result);
            }
            
            public System.IAsyncResult BeginTransferCall(string id, string recruiterUri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = id;
                _args[1] = recruiterUri;
                System.IAsyncResult _result = base.BeginInvoke("TransferCall", _args, callback, asyncState);
                return _result;
            }
            
            public void EndTransferCall(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("TransferCall", _args, result);
            }
            
            public System.IAsyncResult BeginSilentMonitorCall(string id, string sipAddress, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = id;
                _args[1] = sipAddress;
                System.IAsyncResult _result = base.BeginInvoke("SilentMonitorCall", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSilentMonitorCall(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SilentMonitorCall", _args, result);
            }
            
            public System.IAsyncResult BeginBargeIntoCall(string id, string sipAddress, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = id;
                _args[1] = sipAddress;
                System.IAsyncResult _result = base.BeginInvoke("BargeIntoCall", _args, callback, asyncState);
                return _result;
            }
            
            public void EndBargeIntoCall(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("BargeIntoCall", _args, result);
            }
            
            public System.IAsyncResult BeginDispatchCallInQueue(string id, string sipAddress, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = id;
                _args[1] = sipAddress;
                System.IAsyncResult _result = base.BeginInvoke("DispatchCallInQueue", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDispatchCallInQueue(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DispatchCallInQueue", _args, result);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppServiceReference.IPolicyRetriever")]
    public interface IPolicyRetriever {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPolicyRetriever/GetSilverlightPolicy", ReplyAction="http://tempuri.org/IPolicyRetriever/GetSilverlightPolicyResponse")]
        System.IAsyncResult BeginGetSilverlightPolicy(System.AsyncCallback callback, object asyncState);
        
        byte[] EndGetSilverlightPolicy(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolicyRetrieverChannel : PhoneLogic.Core.AppServiceReference.IPolicyRetriever, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSilverlightPolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSilverlightPolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolicyRetrieverClient : System.ServiceModel.ClientBase<PhoneLogic.Core.AppServiceReference.IPolicyRetriever>, PhoneLogic.Core.AppServiceReference.IPolicyRetriever {
        
        private BeginOperationDelegate onBeginGetSilverlightPolicyDelegate;
        
        private EndOperationDelegate onEndGetSilverlightPolicyDelegate;
        
        private System.Threading.SendOrPostCallback onGetSilverlightPolicyCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PolicyRetrieverClient() {
        }
        
        public PolicyRetrieverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolicyRetrieverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyRetrieverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyRetrieverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetSilverlightPolicyCompletedEventArgs> GetSilverlightPolicyCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneLogic.Core.AppServiceReference.IPolicyRetriever.BeginGetSilverlightPolicy(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSilverlightPolicy(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] PhoneLogic.Core.AppServiceReference.IPolicyRetriever.EndGetSilverlightPolicy(System.IAsyncResult result) {
            return base.Channel.EndGetSilverlightPolicy(result);
        }
        
        private System.IAsyncResult OnBeginGetSilverlightPolicy(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneLogic.Core.AppServiceReference.IPolicyRetriever)(this)).BeginGetSilverlightPolicy(callback, asyncState);
        }
        
        private object[] OnEndGetSilverlightPolicy(System.IAsyncResult result) {
            byte[] retVal = ((PhoneLogic.Core.AppServiceReference.IPolicyRetriever)(this)).EndGetSilverlightPolicy(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSilverlightPolicyCompleted(object state) {
            if ((this.GetSilverlightPolicyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSilverlightPolicyCompleted(this, new GetSilverlightPolicyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSilverlightPolicyAsync() {
            this.GetSilverlightPolicyAsync(null);
        }
        
        public void GetSilverlightPolicyAsync(object userState) {
            if ((this.onBeginGetSilverlightPolicyDelegate == null)) {
                this.onBeginGetSilverlightPolicyDelegate = new BeginOperationDelegate(this.OnBeginGetSilverlightPolicy);
            }
            if ((this.onEndGetSilverlightPolicyDelegate == null)) {
                this.onEndGetSilverlightPolicyDelegate = new EndOperationDelegate(this.OnEndGetSilverlightPolicy);
            }
            if ((this.onGetSilverlightPolicyCompletedDelegate == null)) {
                this.onGetSilverlightPolicyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSilverlightPolicyCompleted);
            }
            base.InvokeAsync(this.onBeginGetSilverlightPolicyDelegate, null, this.onEndGetSilverlightPolicyDelegate, this.onGetSilverlightPolicyCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneLogic.Core.AppServiceReference.IPolicyRetriever CreateChannel() {
            return new PolicyRetrieverClientChannel(this);
        }
        
        private class PolicyRetrieverClientChannel : ChannelBase<PhoneLogic.Core.AppServiceReference.IPolicyRetriever>, PhoneLogic.Core.AppServiceReference.IPolicyRetriever {
            
            public PolicyRetrieverClientChannel(System.ServiceModel.ClientBase<PhoneLogic.Core.AppServiceReference.IPolicyRetriever> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSilverlightPolicy(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSilverlightPolicy", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndGetSilverlightPolicy(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("GetSilverlightPolicy", _args, result)));
                return _result;
            }
        }
    }
}
