//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class agentLog
    {
        public int logID { get; set; }
        public string agentEvent { get; set; }
        public System.DateTime eventTime { get; set; }
        public string agentID { get; set; }
        public string eventDscr { get; set; }
        public string jobNum { get; set; }
        public Nullable<int> taskID { get; set; }
        public string callerID { get; set; }
    }
}
