//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public string agentID { get; set; }
        public int teamID { get; set; }
        public string agentName { get; set; }
        public string agentFirstName { get; set; }
        public string agentLastName { get; set; }
        public string dialOutJobNum { get; set; }
        public Nullable<int> dialOutTaskID { get; set; }
        public string SIP { get; set; }
    }
}
