//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    
    public partial class CallbackRpt
    {
        public string jobNum { get; set; }
        public int taskID { get; set; }
        public string taskName { get; set; }
        public string TaskTypeId { get; set; }
        public string tollFreeNumber { get; set; }
        public Nullable<int> CallbackCnt { get; set; }
    }
}
