//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class callback
    {
        public int callbackID { get; set; }
        public string jobNum { get; set; }
        public int taskID { get; set; }
        public string phoneNum { get; set; }
        public string msgScr { get; set; }
        public System.DateTime timeEntered { get; set; }
        public Nullable<int> msgLength { get; set; }
        public string SIP { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    }
}
