//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class callLog
    {
        public int callID { get; set; }
        public string callEvent { get; set; }
        public System.DateTime eventTime { get; set; }
        public string implementationID { get; set; }
        public string callerID { get; set; }
        public string tollFreeNum { get; set; }
        public string jobNum { get; set; }
        public int taskID { get; set; }
        public string eventDscr { get; set; }
    }
}
