//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    
    public partial class callLogDTO
    {
        public string callerid { get; set; }
        public string callevent { get; set; }
        public int callid { get; set; }
        public string eventdscr { get; set; }
        public System.DateTime eventtime { get; set; }
        public string implementationid { get; set; }
        public string jobnum { get; set; }
        public int taskid { get; set; }
        public string tollfreenum { get; set; }
    }
}
