//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class inboundCall
    {
        public int callQueueId { get; set; }
        public string callId { get; set; }
        public string callerId { get; set; }
        public string toTag { get; set; }
        public string fromTag { get; set; }
        public string jobNum { get; set; }
        public System.DateTime timeIn { get; set; }
        public string remoteEndPointUri { get; set; }
    }
}
