//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    
    public partial class LyncCallJob
    {
        public string JobNumber { get; set; }
        public Nullable<int> CallCnt { get; set; }
        public Nullable<int> IncomingCallCnt { get; set; }
        public Nullable<int> OutgoingCallCnt { get; set; }
        public Nullable<int> TotalCallDuration { get; set; }
        public Nullable<int> AvgCallDuration { get; set; }
        public Nullable<int> MaxCallDuration { get; set; }
        public Nullable<int> RecruiterCnt { get; set; }
        public Nullable<int> UniqueCallerCnt { get; set; }
        public Nullable<int> CompleteCnt { get; set; }
        public Nullable<int> LeftMsgCnt { get; set; }
        public string TollFreeNumber { get; set; }
        public Nullable<System.DateTime> FirstCallTime { get; set; }
        public Nullable<System.DateTime> LastCallTime { get; set; }
        public Nullable<int> AbandonedCnt { get; set; }
        public string taskName { get; set; }
        public string TaskTypeId { get; set; }
        public string taskdscr { get; set; }
    }
}
