//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.phones = new HashSet<phone>();
        }
    
        public System.Guid person_id { get; set; }
        public string name_prefix { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string name_suffix { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string gender { get; set; }
        public Nullable<int> source_id { get; set; }
        public string source_key { get; set; }
        public Nullable<bool> is_active { get; set; }
        public System.DateTime updated { get; set; }
        public Nullable<int> contact_pref { get; set; }
        public string updated_user { get; set; }
        public string created_user { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ICollection<phone> phones { get; set; }
    }
}
