//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        public System.Guid phone_id { get; set; }
        public System.Guid person_id { get; set; }
        public string phone_type { get; set; }
        public int phone_order { get; set; }
        public string phone_number { get; set; }
        public Nullable<bool> is_default { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string updated_user { get; set; }
        public string created_user { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual person person { get; set; }
    }
}
