//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    
    public partial class recruiterLogDTO
    {
        public string callerId { get; set; }
        public string callId { get; set; }
        public Nullable<System.DateTime> eventTime { get; set; }
        public string jobNumber { get; set; }
        public int logid { get; set; }
        public string recruiterSip { get; set; }
        public string tollFreeNumber { get; set; }
    }
}
