//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    
    public partial class recruiterLogDTO
    {
        public int StartLogId { get; set; }
        public string JobNumber { get; set; }
        public string callerId { get; set; }
        public string callId { get; set; }
        public Nullable<System.DateTime> callStartTime { get; set; }
        public Nullable<System.DateTime> recruiterConnectTime { get; set; }
        public string preconnectDuration { get; set; }
        public string recruiterCallDuration { get; set; }
        public string recruiterSip { get; set; }
        public string totalCallDuration { get; set; }
        public Nullable<System.DateTime> callEndTime { get; set; }
        public string tollFreeNumber { get; set; }
    }
}
