//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    
    public partial class rptGetTodayCallLogSummaryResult
    {
        public string jobNum { get; set; }
        public int taskID { get; set; }
        public string taskName { get; set; }
        public string taskDscr { get; set; }
        public string taskTypeID { get; set; }
        public string taskStatusID { get; set; }
        public string tollfreenumber { get; set; }
        public Nullable<int> InboundCalls { get; set; }
        public Nullable<int> NoAgents { get; set; }
        public Nullable<int> Abandoned { get; set; }
        public Nullable<int> LeftMessage { get; set; }
        public Nullable<int> CallBack { get; set; }
        public Nullable<int> PlacedCall { get; set; }
    }
}
