//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    
    public partial class rptInboundCallByHourResult
    {
        public string WorkDate { get; set; }
        public Nullable<int> Before_9am { get; set; }
        public Nullable<int> C9_am { get; set; }
        public Nullable<int> C10_am { get; set; }
        public Nullable<int> C11_am { get; set; }
        public Nullable<int> C12_pm { get; set; }
        public Nullable<int> C1_pm { get; set; }
        public Nullable<int> C2_pm { get; set; }
        public Nullable<int> C3_pm { get; set; }
        public Nullable<int> C4_pm { get; set; }
        public Nullable<int> C5_pm { get; set; }
        public Nullable<int> C6_pm { get; set; }
        public Nullable<int> C7_pm { get; set; }
        public Nullable<int> C8_pm { get; set; }
        public Nullable<int> C9_pm { get; set; }
        public Nullable<int> C10_pm { get; set; }
        public Nullable<int> after_10pm { get; set; }
    }
}
