//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogic.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PhoneLogicTaskAgent
    {
        public string jobNum { get; set; }
        public int taskID { get; set; }
        public string taskName { get; set; }
        public string taskDscr { get; set; }
        public string taskTypeID { get; set; }
        public string sip { get; set; }
        public string tollFreeNumber { get; set; }
    }
}
